<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public static function orderByNom(EntityRepository $er){
        return $er->createQueryBuilder('c')
            ->orderBy('c.nom', 'ASC');
    }
}
