<?php

namespace App\Repository;

/**
 * ChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampRepository extends \Doctrine\ORM\EntityRepository
{
}
