<?php

namespace App\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function commentairesNonValides(){
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.valide = 0')
            ->andWhere('c.corbeille = 0')
            ->orderBy('c.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
