<?php

namespace App\Repository;

/**
 * LangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangueRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombreTotal(){
        $qb = $this
            ->createQueryBuilder('l')
            ->select('count(l.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
