<?php

namespace App\Repository;

/**
 * MenuPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuPageRepository extends \Doctrine\ORM\EntityRepository
{
}
