<?php

namespace App\Repository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Symfony\Component\HttpFoundation\Request;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function pagesPublieesQB(){
        return $this
            ->createQueryBuilder('p')
                ->where('p.corbeille = 0')
                ->andWhere('p.active = 1')
                //->andWhere('p.langue = :langue')
                //->setParameter('langue', $langue)
                ->orderBy('p.datePublication', 'DESC');
    }

    public function pagesPubliees($langue){
        $timestamp = new \DateTime();
        $date = $timestamp->format('Y-m-d H:i:s');

        $qb = $this
            ->createQueryBuilder('p')
                ->where('p.corbeille = 0')
                ->andWhere('p.active = 1')
                ->andWhere('p.langue = :langue')
                ->andWhere('p.datePublication < :date')
                ->andWhere('p.dateDepublication > :date OR p.dateDepublication IS NULL')
                    ->setParameters(array('langue' => $langue, 'date' => $date))
            ->orderBy('p.datePublication', 'DESC')
            ->setMaxResults(5);

        return $qb->getQuery()->getResult();
    }
}
