<?php

namespace App\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function pagesPubliees($langue, $racine){
        $timestamp = new \DateTime();
        $date = $timestamp->format('Y-m-d H:i:s');

        $qb = $this
            ->createQueryBuilder('p')
                ->where('p.corbeille = 0')
                ->andWhere('p.active = 1')
                ->andWhere('p.langue = :langue')
                ->andWhere('p.datePublication < :date')
                ->andWhere('p.dateDepublication > :date OR p.dateDepublication IS NULL')
                    ->setParameters(array('langue' => $langue, 'date' => $date))
            ->orderBy('p.datePublication', 'DESC')
            ->setMaxResults(5);

        if($racine){
            $qb->andWhere('p.pageParent IS NULL');
        }

        return $qb->getQuery()->getResult();
    }
}
