<?php

namespace App\Repository;

/**
 * SEOCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEOCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
