<?php

namespace App\Repository;

/**
 * SEOPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEOPageRepository extends \Doctrine\ORM\EntityRepository
{
}
