<?php

namespace App\Repository;

/**
 * SEORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEORepository extends \Doctrine\ORM\EntityRepository
{
}
