<?php

namespace App\Repository;

/**
 * SEOTypeCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEOTypeCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
