<?php

namespace App\Repository;

/**
 * TypeCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
