<?php

namespace App\Repository;

/**
 * TypeModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
