<?php

namespace App\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUtilisateursAvecRole($role){
        $qb = $this
            ->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', '%"' . $role . '"%');

        return $qb->getQuery()->getResult();
    }

    public function triDateDerniereConnexion(){
        $qb = $this
            ->createQueryBuilder('u')
            ->orderBy('u.lastLogin', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
