infos:
    nom: Nina
    auteur: la couleur du Zèbre
    site: https://www.lacouleurduzebre.com
    description: Thème par défaut du CMS Nina
champs:
    #Couleurs
    couleur1: "#0791B3"
    couleur2: "#A1BA1D"
    couleur3: "#F29400"
    #Polices à importer
    polices: {}
    #H1
    couleurH1: "$couleur"
    policeH1: ""
    taillePoliceH1: "16px"
    #H2
    couleurH2: "$couleur"
    policeH2: ""
    taillePoliceH2: "16px"
    #H3
    couleurH3: "$couleur"
    policeH3: ""
    taillePoliceH3: "16px"
    #H4
    couleurH4: $couleur"
    policeH4: ""
    taillePoliceH4: "16px"
    #Textes
    couleurTextes: "$couleur"
    policeTextes: ""
    tailleTextes: "16px"
    #Liens
    couleurLiens: "$couleur"
    #Formulaires
    couleurFormulaires: "$couleur"
    #Étiquettes de catégorie
    couleurCategories: "$couleur"
#blocs:
#    Titre:
#        classes:
#            Test: test