infos:
    nom: Nina
    auteur: la couleur du Zèbre
    site: https://www.lacouleurduzebre.com
    description: Thème par défaut du CMS Nina
champs:
    #Couleurs
    couleur1: "#0791B3"
    couleur2: "#A1BA1D"
    couleur3: "#F29400"
    #Polices à importer
    polices:
        - Roboto
    #H1
    couleurH1: $couleur1
    policeH1: Roboto
    taillePoliceH1: 4rem
    #H2
    couleurH2: $couleur1
    policeH2: Roboto
    taillePoliceH2: 3rem
    #H3
    couleurH3: $couleur1
    policeH3: Roboto
    taillePoliceH3: 2.5rem
    #H4
    couleurH4: $couleur1
    policeH4: Roboto
    taillePoliceH4: 2rem
    #Textes
    couleurTextes: $couleur1
    policeTextes: Roboto
    tailleTextes: 1.6rem
    #Liens
    couleurLiens: $couleur2
    #Formulaires
    couleurFormulaires: $couleur1
    #Étiquettes de catégorie
    couleurCategories: $couleur1
#blocs:
#    Titre:
#        classes:
#            Test: test