easy_admin:
    entities:
        Langue:
            class: App\Entity\Langue
            controller: App\Controller\Back\Admin\LangueAdminController
            label: 'Langue'
            labels: 'Langues'
            labelDeterminant: 'une langue'
            list:
                sort: 'abreviation'
                fields:
                    - nom
                    - abreviation
                    - active
                    - defaut
            search:
                sort: 'abreviation'
                fields:
                    - nom
            show:
                fields:
                    - abreviation
                    - nom
                    - active
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - nom
                    - { property: 'abreviation', label: 'Abréviation', type_options: { help: 'deux lettres, de préférence en minuscules' } }
                    - { property: 'code', label: 'Code de la langue sous la forme xx-XX' }
                    - { property: 'metaTitre', label: 'Meta-titre général pour cette langue' }
                    - { property: 'metaDescription', label: 'Meta-description générale pour cette langue', type_options: { attr: { class: 'notTinymce' } } }
                    #Page d'accueil : dans AdminController, uniquement durant l'édition
            edit:
                title: nom